import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
const products = [
 {name:"ASUS ROG Strix G16 Gaming Laptop",slug:"asus-rog-strix-g16",category:"Gaming Laptops",brand:"ASUS",price:419999,oldPrice:449999,stock:8,image:"https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=1000&q=85",shortDesc:"Powerful RTX gaming performance in a premium 16-inch chassis.",description:"Built for competitive gaming and demanding creative work with excellent cooling and a high refresh-rate display.",specs:"Intel Core i9 Processor\n16GB DDR5 RAM\n1TB NVMe SSD\nNVIDIA RTX Graphics\n16-inch 165Hz Display",featured:true},
 {name:"Apple MacBook Air 15-inch",slug:"apple-macbook-air-15",category:"MacBooks",brand:"Apple",price:349999,oldPrice:369999,stock:12,image:"https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1000&q=85",shortDesc:"Thin, silent and powerful MacBook for work and study.",description:"A lightweight all-day laptop with a beautiful display, long battery life and excellent everyday performance.",specs:"Apple Silicon\n16GB Unified Memory\n512GB SSD\n15-inch Liquid Retina\nAll-day Battery",featured:true},
 {name:"Dell Latitude Business Laptop",slug:"dell-latitude-business",category:"Business Laptops",brand:"Dell",price:184999,oldPrice:199999,stock:18,image:"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1000&q=85",shortDesc:"Reliable business laptop with secure, professional performance.",description:"Designed for office teams, remote workers and professionals who need reliability and portability.",specs:"Intel Core i7\n16GB RAM\n512GB SSD\n14-inch Full HD\nBacklit Keyboard",featured:true},
 {name:"HP Pavilion 15 Laptop",slug:"hp-pavilion-15",category:"Laptops",brand:"HP",price:169999,oldPrice:179999,stock:10,image:"https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1000&q=85",shortDesc:"A balanced laptop for students, office and home use.",description:"Modern design, smooth multitasking and a comfortable full-size keyboard for daily productivity.",specs:"Intel Core i5\n8GB RAM\n512GB SSD\n15.6-inch Full HD\nWindows 11",featured:false},
 {name:"Lenovo ThinkPad E14",slug:"lenovo-thinkpad-e14",category:"Business Laptops",brand:"Lenovo",price:209999,oldPrice:224999,stock:6,image:"https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=1000&q=85",shortDesc:"Durable ThinkPad experience with excellent keyboard and security.",description:"A dependable productivity machine for business users, developers and field professionals.",specs:"AMD Ryzen 7\n16GB RAM\n512GB SSD\n14-inch IPS Display\nFingerprint Reader",featured:true},
 {name:"Logitech Wireless Keyboard & Mouse",slug:"logitech-wireless-combo",category:"Accessories",brand:"Logitech",price:8999,oldPrice:9999,stock:35,image:"https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1000&q=85",shortDesc:"Comfortable wireless combo for home and office desks.",description:"A practical, reliable keyboard and mouse set with long battery life and simple plug-and-play setup.",specs:"2.4GHz Wireless\nFull-size Keyboard\nOptical Mouse\nUSB Receiver\nLong Battery Life",featured:false}
];
const slides = [
 {heading:"Next-Gen Gaming Laptops",description:"RTX-powered performance for competitive players and creators. Genuine units, expert support.",image:"https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=1600&q=80",btn1Label:"Shop Gaming",btn1Link:"/products?category=Gaming%20Laptops",btn2Label:"View All",btn2Link:"/products",sortOrder:1,active:true},
 {heading:"MacBooks You Can Trust",description:"Apple silicon power for work and study — thin, silent and built to last. Nationwide delivery.",image:"https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1600&q=80",btn1Label:"Shop MacBooks",btn1Link:"/products?category=MacBooks",btn2Label:"Explore Deals",btn2Link:"/products",sortOrder:2,active:true},
 {heading:"Upgrade Your Setup",description:"Desktops, accessories, storage and networking — everything to power your ambition.",image:"https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1600&q=80",btn1Label:"Browse Store",btn1Link:"/products",btn2Label:"Best Sellers",btn2Link:"/products?sort=price-desc",sortOrder:3,active:true},
];

async function main(){
 for(const p of products) await prisma.product.upsert({where:{slug:p.slug},update:p,create:p});
 if(await prisma.slide.count()===0){ for(const s of slides) await prisma.slide.create({data:s}); }
}
main().finally(()=>prisma.$disconnect());
